#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Parser.y"

#include "Parser.tab.h"
#include <stdio.h>
#include <string.h>
#include <iostream>
#include "sym_table.h"
#include <time.h>
#include <string>
#include <unistd.h>
#include "block_stack.h"
#include "llvm_generator.h"
//Prototipos y externos, se rompe todo si no estan...
int yylex();
extern FILE* yyin;
void yyerror(char* s);
char* to_char_ptr (const string& str);
void semantic_error(semantic_result res);
semantic_result type_system_numeric(char* type1, char* type2, char* op);
semantic_result get_type_relation(string type1, string type2);
extern char lineBuffer[1000];
extern int yylineno;

sym_table Table;
semantic_result res;
block_stack block_stack;
llvm_generator* excalibur_builder = new llvm_generator();
int error_count =0;

#line 30 "Parser.y"
typedef union
{
    char *text;
    void* expression_node;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	READ	258
#define	WRITE	259
#define	WHILE	260
#define	IF	261
#define	TYPE	262
#define	BOOL	263
#define	END	264
#define	SUM	265
#define	MINUS	266
#define	DIV	267
#define	MULT	268
#define	REL_OP	269
#define	ASSIGN	270
#define	SEMI_COLON	271
#define	COLON	272
#define	COMMA	273
#define	LEFT_GROUP	274
#define	RIGHT_GROUP	275
#define	STRING	276
#define	ID	277
#define	FLOATING	278
#define	INTEGER	279
#define	UNDEFINED	280


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int READ;
static const int WRITE;
static const int WHILE;
static const int IF;
static const int TYPE;
static const int BOOL;
static const int END;
static const int SUM;
static const int MINUS;
static const int DIV;
static const int MULT;
static const int REL_OP;
static const int ASSIGN;
static const int SEMI_COLON;
static const int COLON;
static const int COMMA;
static const int LEFT_GROUP;
static const int RIGHT_GROUP;
static const int STRING;
static const int ID;
static const int FLOATING;
static const int INTEGER;
static const int UNDEFINED;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,READ=258
	,WRITE=259
	,WHILE=260
	,IF=261
	,TYPE=262
	,BOOL=263
	,END=264
	,SUM=265
	,MINUS=266
	,DIV=267
	,MULT=268
	,REL_OP=269
	,ASSIGN=270
	,SEMI_COLON=271
	,COLON=272
	,COMMA=273
	,LEFT_GROUP=274
	,RIGHT_GROUP=275
	,STRING=276
	,ID=277
	,FLOATING=278
	,INTEGER=279
	,UNDEFINED=280


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::READ=258;
const int YY_parse_CLASS::WRITE=259;
const int YY_parse_CLASS::WHILE=260;
const int YY_parse_CLASS::IF=261;
const int YY_parse_CLASS::TYPE=262;
const int YY_parse_CLASS::BOOL=263;
const int YY_parse_CLASS::END=264;
const int YY_parse_CLASS::SUM=265;
const int YY_parse_CLASS::MINUS=266;
const int YY_parse_CLASS::DIV=267;
const int YY_parse_CLASS::MULT=268;
const int YY_parse_CLASS::REL_OP=269;
const int YY_parse_CLASS::ASSIGN=270;
const int YY_parse_CLASS::SEMI_COLON=271;
const int YY_parse_CLASS::COLON=272;
const int YY_parse_CLASS::COMMA=273;
const int YY_parse_CLASS::LEFT_GROUP=274;
const int YY_parse_CLASS::RIGHT_GROUP=275;
const int YY_parse_CLASS::STRING=276;
const int YY_parse_CLASS::ID=277;
const int YY_parse_CLASS::FLOATING=278;
const int YY_parse_CLASS::INTEGER=279;
const int YY_parse_CLASS::UNDEFINED=280;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		71
#define	YYFLAG		-32768
#define	YYNTBASE	26

#define YYTRANSLATE(x) ((unsigned)(x) <= 280 ? yytranslate[x] : 46)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     6,     8,    10,    14,    18,    22,    26,
    29,    30,    32,    34,    36,    39,    43,    48,    53,    55,
    57,    59,    61,    63,    66,    67,    71,    75,    78,    79,
    83,    87,    89,    91,    93,    97,    99,   101,   103
};

static const short yyrhs[] = {    -1,
    27,    26,     0,    32,     0,    31,     0,    29,     0,     5,
    44,    17,     0,    28,    26,     9,     0,     6,    44,    17,
     0,    30,    26,     9,     0,    33,    16,     0,     0,    35,
     0,    34,     0,    36,     0,     7,    22,     0,    22,    15,
    38,     0,     3,    19,    22,    20,     0,     4,    19,    37,
    20,     0,    21,     0,    22,     0,    21,     0,    39,     0,
     8,     0,    41,    40,     0,     0,    10,    41,    40,     0,
    11,    41,    40,     0,    43,    42,     0,     0,    13,    43,
    42,     0,    12,    43,    42,     0,    22,     0,    24,     0,
    23,     0,    19,    39,    20,     0,    45,     0,     8,     0,
    22,     0,    39,    14,    39,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    72,    74,    77,    83,    95,   110,   132,   138,   159,   166,
   170,   172,   173,   174,   178,   202,   290,   304,   307,   314,
   330,   346,   354,   373,   395,   397,   433,   474,   495,   497,
   534,   573,   586,   590,   594,   600,   613,   624,   644
};

static const char * const yytname[] = {   "$","error","$illegal.","READ","WRITE",
"WHILE","IF","TYPE","BOOL","END","SUM","MINUS","DIV","MULT","REL_OP","ASSIGN",
"SEMI_COLON","COLON","COMMA","LEFT_GROUP","RIGHT_GROUP","STRING","ID","FLOATING",
"INTEGER","UNDEFINED","function_behavior","function_behavior_alpha","loop_init",
"loop","if_init","if_statement","function_line","function_line_alpha","var_init",
"var_assign","method_call","write_parameter","expression","numerical_expression",
"numerical_expression_prime","term","term_prime","factor","bool_expression",
"rel_expression",""
};
#endif

static const short yyr1[] = {     0,
    26,    26,    27,    27,    27,    28,    29,    30,    31,    32,
    33,    33,    33,    33,    34,    35,    36,    36,    37,    37,
    38,    38,    38,    39,    40,    40,    40,    41,    42,    42,
    42,    43,    43,    43,    43,    44,    44,    44,    45
};

static const short yyr2[] = {     0,
     0,     2,     1,     1,     1,     3,     3,     3,     3,     2,
     0,     1,     1,     1,     2,     3,     4,     4,     1,     1,
     1,     1,     1,     2,     0,     3,     3,     2,     0,     3,
     3,     1,     1,     1,     3,     1,     1,     1,     3
};

static const short yydefact[] = {     1,
     0,     0,     0,     0,     0,     0,     1,     1,     5,     1,
     4,     3,     0,    13,    12,    14,     0,     0,    37,     0,
    32,    34,    33,     0,    25,    29,     0,    36,     0,    15,
     0,     2,     0,     0,    10,     0,    19,    20,     0,    32,
     0,     0,     0,     0,    24,     0,     0,    28,     6,     8,
    23,    21,    16,    22,     7,     9,    17,    18,    35,    39,
    25,    25,    29,    29,    26,    27,    31,    30,     0,     0,
     0
};

static const short yydefgoto[] = {    32,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    39,    53,    24,    45,    25,    48,    26,    27,    28
};

static const short yypact[] = {    -2,
    24,    25,     8,     8,   -16,    30,    -2,    -2,-32768,    -2,
-32768,-32768,    31,-32768,-32768,-32768,    26,   -13,-32768,    14,
    29,-32768,-32768,    35,    18,     0,    33,-32768,    34,-32768,
     2,-32768,    43,    44,-32768,    36,-32768,-32768,    37,-32768,
    38,    14,    14,    14,-32768,    14,    14,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    18,    18,     0,     0,-32768,-32768,-32768,-32768,    54,    55,
-32768
};

static const short yypgoto[] = {     7,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -20,   -43,    -9,   -24,    -5,    56,-32768
};


#define	YYLAST		60


static const short yytable[] = {    41,
     1,     2,     3,     4,     5,    30,    69,    37,    38,    51,
    54,    46,    47,   -11,    33,    19,    34,    65,    66,     6,
    20,    60,    52,    40,    22,    23,    20,    43,    44,    21,
    22,    23,    20,    61,    62,    40,    22,    23,    67,    68,
    63,    64,    17,    18,    31,   -38,    35,    36,    42,    49,
    50,    55,    56,    70,    71,    57,    58,    59,     0,    29
};

static const short yycheck[] = {    20,
     3,     4,     5,     6,     7,    22,     0,    21,    22,     8,
    31,    12,    13,    16,     8,     8,    10,    61,    62,    22,
    19,    42,    21,    22,    23,    24,    19,    10,    11,    22,
    23,    24,    19,    43,    44,    22,    23,    24,    63,    64,
    46,    47,    19,    19,    15,    17,    16,    22,    14,    17,
    17,     9,     9,     0,     0,    20,    20,    20,    -1,     4
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 79 "Parser.y"
{
        printf("Line: ");printf(lineBuffer); printf("\n");
        
    ;
    break;}
case 4:
#line 84 "Parser.y"
{
        printf("If: ");printf(lineBuffer); printf("\n");

        res = Table.delete_scope();
        if(res.error)
        {
            semantic_error(res);
        }
        block_stack.delete_if_block();
        
    ;
    break;}
case 5:
#line 96 "Parser.y"
{
        printf("loop: ");printf(lineBuffer); printf("\n");
        res = Table.delete_scope();
        if(res.error)
        {
            semantic_error(res);
        }
        block_stack.delete_loop_block();
        
    ;
    break;}
case 6:
#line 112 "Parser.y"
{
        printf("loop_init\n");
        res = Table.new_scope();
        if(res.error)
            semantic_error(res);
        else{
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[-1].expression_node);
            res = *casted_ptr;
            if(res.error)
                semantic_error(res);
            else{
                string quadruple = res.IR_node_quadruple;
                string condition = res.IR_node_identifier;
                block_stack.new_loop_block(quadruple, condition);
                                
            }
        }
    ;
    break;}
case 8:
#line 140 "Parser.y"
{
        printf("if_init\n");
        res = Table.new_scope();
        if(res.error)
            semantic_error(res);
        else{
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[-1].expression_node);
            res = *casted_ptr;
            if(res.error)
                semantic_error(res);
            else{
                string quadruple = res.IR_node_quadruple;
                string condition = res.IR_node_identifier;
                block_stack.new_if_block(quadruple, condition);
                                
            }
        }            
    ;
    break;}
case 15:
#line 180 "Parser.y"
{
        int sym_link = excalibur_builder->add_static_declaration(yyvsp[-1].text);
        res = Table.insert(yyvsp[0].text, yyvsp[-1].text, sym_link);
        if(res.error)
            semantic_error(res);
        string type(yyvsp[-1].text);
        string id(yyvsp[0].text);
        string new_line = type+" "+id;
        block_stack.add_line(new_line);
    ;
    break;}
case 16:
#line 204 "Parser.y"
{
        string type1 = "";
        string type2 = "";
        int variable_link=0;
        string tree_result_data;
        int tree_result_link;
        bool tree_result_is_constant;

        res = Table.get_type(yyvsp[-2].text);
        if(res.error)
        {
            semantic_error(res);
            type1 = "undefined";
        }
        else
        {
            type1 = res.attribute;
            variable_link = res.sym_link;
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[0].expression_node);
            res = *casted_ptr;
            if(res.error)
            {
                semantic_error(res);
                type2 = "undefined";
            }
            else
            {
                type2 = res.attribute;
                tree_result_is_constant = res.is_constant;
                if(tree_result_is_constant)
                    tree_result_data = res.data;
                else
                    tree_result_link = res.sym_link;
                
                res = get_type_relation(type1, type2);
                if(res.error)
                {
                    semantic_error(res);
                }
                else//Write IR code
                {
                    //Type conversions
                    if(type1 == "float"){
                        if(type2 == "int"){
                            if(tree_result_is_constant){
                                tree_result_data = strcat(to_char_ptr(tree_result_data), ".0");
                            }else{
                                tree_result_link = excalibur_builder->int_to_double(tree_result_link);
                            }
                            type2 = "float";
                        }
                        //bools and strings do not get here
                        if(tree_result_is_constant){
                            excalibur_builder->store_value_in_variable(variable_link,"float", yyvsp[-2].text, tree_result_data);
                        }else{
                            excalibur_builder->store_link_in_variable(variable_link,"float", tree_result_link);
                        }
                    }else if(type1 == "int"){
                        if(type2 == "float"){
                            if(tree_result_is_constant){
                                double casted_tree_data = stod(tree_result_data);
                                int casted_tree_data_int = static_cast<int> (casted_tree_data);
                                tree_result_data = to_string(casted_tree_data_int);
                            }else{
                                tree_result_link = excalibur_builder->double_to_int(tree_result_link);
                            }
                        type2 = "int";
                        }
                    }

                    //storing values
                    if(tree_result_is_constant){
                        excalibur_builder->store_value_in_variable(variable_link,type1, yyvsp[-2].text, tree_result_data);
                    }else{
                        if(type1 == "string"){
                            excalibur_builder->store_link_to_string_variable(variable_link, tree_result_link);
                        }else{
                            excalibur_builder->store_link_in_variable(variable_link, type1, tree_result_link);
                        }
                    }
                }
            }
        }
    ;
    break;}
case 17:
#line 293 "Parser.y"
{
        res = Table.get_type(yyvsp[-1].text);
        if(res.error)
            semantic_error(res);
        else{
            string id(yyvsp[-1].text);
            string new_line("@t1 = read()\n"+id+" = @t1");
            block_stack.add_line(new_line);
        }
    ;
    break;}
case 19:
#line 309 "Parser.y"
{
        string id(yyvsp[0].text);
        string new_line("@t1 = "+id+"\nwrite(@t1)");
        block_stack.add_line(new_line);
    ;
    break;}
case 20:
#line 315 "Parser.y"
{
        res = Table.get_type(yyvsp[0].text);
        if(res.error)
            semantic_error(res);
        else{
            string id(yyvsp[0].text);
            string new_line("@t1 = "+id+"\nwrite(@t1)");
            block_stack.add_line(new_line);
        }
    ;
    break;}
case 21:
#line 332 "Parser.y"
{
        string text(yyvsp[0].text);
        //eliminate the quotes
        text.erase(0,1);
        text.erase(text.length()-1,1);
        cout<<"text:"<<text<<endl;
        semantic_result* res = new semantic_result;
        res->error = false;
        res->attribute = "string";
        res->data = to_char_ptr(text);
        res->is_constant = true;
        res->sym_link = -1;
        yyval.expression_node = res; 
    ;
    break;}
case 22:
#line 347 "Parser.y"
{
        semantic_result Node_res;        
        node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
        Node_res = casted_ptr -> define_type(0, excalibur_builder); 
        semantic_result* res = new semantic_result(Node_res);
        yyval.expression_node = res;
    ;
    break;}
case 23:
#line 355 "Parser.y"
{
    string bool_value(yyvsp[0].text);
    semantic_result* res = new semantic_result;
    res->error = false;
    res->attribute = "bool";
    if(bool_value == "true")
        res->data = "1";
    else
        res->data = "0";
    res->is_constant = true;
    res->sym_link = -1;
    yyval.expression_node = res;
;
    break;}
case 24:
#line 375 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            yyval.expression_node = yyvsp[-1].expression_node;
        }
        else
        {
            //assigning $1 (factor) as the leftmost leave of the $2 (term_prime) tree
            //first, two auxiliar pointer casted as node*
            node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
            node* casted_ptr2 = static_cast<node *> (yyvsp[-1].expression_node);

            //Then,from casted_ptr we call insert_left_most
            casted_ptr -> insert_left_most(casted_ptr2);
            yyval.expression_node = casted_ptr;            
        }
    ;
    break;}
case 25:
#line 396 "Parser.y"
{yyval.expression_node = nullptr;
    break;}
case 26:
#line 398 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);
            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 27:
#line 434 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 28:
#line 476 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            yyval.expression_node = yyvsp[-1].expression_node;
        }
        else
        {
            //assigning $1 (factor) as the leftmost leave of the $2 (term_prime) tree
            //first, two auxiliar pointer casted as node*
            node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
            node* casted_ptr2 = static_cast<node *> (yyvsp[-1].expression_node);

            //Then,from casted_ptr we call insert_left_most
            casted_ptr -> insert_left_most(casted_ptr2);
            yyval.expression_node = casted_ptr;            
        }
    ;
    break;}
case 29:
#line 496 "Parser.y"
{yyval.expression_node = nullptr;
    break;}
case 30:
#line 498 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 31:
#line 535 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 (factor) node, here it's being assigned as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 32:
#line 575 "Parser.y"
{            
        res = Table.get_type(yyvsp[0].text);
        if(!res.error)
        {
            yyval.expression_node = new node(yyvsp[0].text,to_char_ptr(res.attribute), res.sym_link);
        }
        else
        {
            yyval.expression_node = new node(yyvsp[0].text);
        }
    ;
    break;}
case 33:
#line 587 "Parser.y"
{
        yyval.expression_node = new node(yyvsp[0].text,"int", true);
    ;
    break;}
case 34:
#line 591 "Parser.y"
{
        yyval.expression_node = new node(yyvsp[0].text,"float", true);
    ;
    break;}
case 35:
#line 595 "Parser.y"
{
        yyval.expression_node = yyvsp[-1].expression_node;
    ;
    break;}
case 36:
#line 602 "Parser.y"
{
        // semantic_result* casted_ptr = static_cast<semantic_result *> ($1);
        // res = *casted_ptr;
        // if(res.error){
        //     $$ = $1;
        // }
        // else{
        //     $$ = $1;
        // }
        yyval.expression_node = yyvsp[0].expression_node;
    ;
    break;}
case 37:
#line 614 "Parser.y"
{
        string bool_value(yyvsp[0].text);
        string new_line("@t1 = " +bool_value);
        semantic_result* res_bool = new semantic_result;
        res_bool->error = false;
        res_bool->attribute = "bool";
        res_bool->IR_node_quadruple = new_line;
        res_bool->IR_node_identifier = "@t1";        
        yyval.expression_node = res_bool;
    ;
    break;}
case 38:
#line 625 "Parser.y"
{
        semantic_result* res_bool = new semantic_result;
        res = Table.get_type(yyvsp[0].text);
        if(res.error){
            semantic_error(res);
            res_bool->error = true;
            yyval.expression_node = res_bool;
        }    
        else{
            string id(yyvsp[0].text);
            string new_line("@t1 = "+id);
            res_bool->error = false;
            res_bool->attribute = "bool";
            res_bool->IR_node_quadruple = new_line;
            res_bool->IR_node_identifier = "@t1";
            yyval.expression_node = res_bool;
        }
    ;
    break;}
case 39:
#line 646 "Parser.y"
{
        semantic_result* res_bool = new semantic_result;
        node* casted_ptr = static_cast<node *> (yyvsp[-2].expression_node);
        node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);
        res = casted_ptr -> define_type(0, excalibur_builder);
        if(res.error){
            semantic_error(res);
            res_bool->error = true;
            yyval.expression_node = res_bool;
        }
        else
        {
            string quadruple1 = res.IR_node_quadruple;
            string identifier1 = res.IR_node_identifier;
            res = casted_ptr2 -> define_type(1, excalibur_builder);
            if(res.error){
                semantic_error(res);
                res_bool->error = true;
                yyval.expression_node = res_bool;    
            }else{
                string quadruple2 = res.IR_node_quadruple;
                string identifier2 = res.IR_node_identifier;
                string rel_op(yyvsp[-1].text);
                string new_line("@t1 = "+identifier1+rel_op+identifier2);
                new_line = quadruple1+"\n"+quadruple2+"\n"+new_line;
                res_bool->error = false;
                res_bool->attribute = "bool";
                res_bool->IR_node_quadruple = new_line;
                res_bool->IR_node_identifier = "@t1";
                yyval.expression_node = res_bool;
            } 
        }        
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 702 "Parser.y"


void semantic_error(semantic_result res)
{
//     if(!semantic_error_counter)
//     {
        error_count++;
        cout<<"\n---semantic error in line "<<yylineno<<" : << "<<lineBuffer<< " >> "<<res.message<<" ---";
    //     semantic_error_counter = true;
    // }

}

void yyerror (char* s)
{
    error_count++;
    printf("\n---%s in line %d : << %s >>---", s, yylineno, lineBuffer);
}

char* to_char_ptr (const string& str)
{
    char* char_ptr = new char[str.length() +1];
    strcpy(char_ptr, str.c_str());
    return char_ptr;
}

semantic_result get_type_relation(string type1, string type2)
{
    semantic_result res;
    if(type1 == "string" && type2 == "string")
    {
        res.error = false;
    }
    else if(type1 == "int" && type2 == "int")
    {
        res.error = false;
    }
    else if(type1 == "float" && type2 == "float")
    {
        res.error = false;
    }
    else if(type1 == "bool" && type2 == "bool")
    {
        res.error = false;
    }
    else if(type1 == "float" && type2 == "int")
    {
        res.error = false;
    }
    else if(type1 == "int" && type2 == "float")
    {
        res.error = false;
    }
    else
    {
        res.error = true;
        res.message = "Incompatible types in assigning operation.";
    }
    return res;
}

int main(int argc, char** argv) {
    clock_t start_time, end_time;
    double execution_time;

    start_time = clock();  // Get the initial clock time

    FILE* file = fopen(argv[1], "r");
    if (!file) {
        perror("fopen");
        return 1;
    }

    yyin = file;

    yyparse();

    fclose(file);

    end_time = clock();  // Get the final clock time*

    // Calculate the execution time in seconds
    execution_time = (double)(end_time - start_time) / CLOCKS_PER_SEC;

    printf("Finalizado...\n");
    if(error_count==0){
        block_stack.write_file("IR.txt");
        excalibur_builder->print_llvm_code();
    }

    // if (B == 1)
    //     printf("\n\nParseo no finalizado debido a errores, tiempo de ejecucion: %.20f segundos\n", execution_time);
    // else
    //     printf("\n\nParseo completado sin errores, tiempo de ejecucion: %.20f segundos\n", execution_time);

    return 0;
}
