#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Parser.y"

#include "Parser.tab.h"
#include <stdio.h>
#include <string.h>
#include <iostream>
#include "sym_table.h"
#include <time.h>
#include <string>
#include <unistd.h>
#include "block_stack.h"
#include "llvm_generator.h"
//Prototipos y externos, se rompe todo si no estan...
int yylex();
extern FILE* yyin;
void yyerror(char* s);
char* to_char_ptr (const string& str);
void semantic_error(semantic_result res);
semantic_result type_system_numeric(char* type1, char* type2, char* op);
semantic_result get_type_relation(string type1, string type2);
semantic_result get_type_relation_for_rel_ops(string type1, string type2);
extern char lineBuffer[1000];
extern int yylineno;

sym_table Table;
semantic_result res;
semantic_result res_MYWAY;
block_stack block_stack;
llvm_generator* excalibur_builder = new llvm_generator();
int error_count =0;

#line 32 "Parser.y"
typedef union
{
    char *text;
    void* expression_node;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NEW_LINE	258
#define	READ	259
#define	WRITE	260
#define	WHILE	261
#define	IF	262
#define	TYPE	263
#define	BOOL	264
#define	END	265
#define	SUM	266
#define	MINUS	267
#define	DIV	268
#define	MULT	269
#define	REL_OP	270
#define	ASSIGN	271
#define	SEMI_COLON	272
#define	COLON	273
#define	COMMA	274
#define	LEFT_GROUP	275
#define	RIGHT_GROUP	276
#define	STRING	277
#define	ID	278
#define	FLOATING	279
#define	INTEGER	280
#define	UNDEFINED	281


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NEW_LINE;
static const int READ;
static const int WRITE;
static const int WHILE;
static const int IF;
static const int TYPE;
static const int BOOL;
static const int END;
static const int SUM;
static const int MINUS;
static const int DIV;
static const int MULT;
static const int REL_OP;
static const int ASSIGN;
static const int SEMI_COLON;
static const int COLON;
static const int COMMA;
static const int LEFT_GROUP;
static const int RIGHT_GROUP;
static const int STRING;
static const int ID;
static const int FLOATING;
static const int INTEGER;
static const int UNDEFINED;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NEW_LINE=258
	,READ=259
	,WRITE=260
	,WHILE=261
	,IF=262
	,TYPE=263
	,BOOL=264
	,END=265
	,SUM=266
	,MINUS=267
	,DIV=268
	,MULT=269
	,REL_OP=270
	,ASSIGN=271
	,SEMI_COLON=272
	,COLON=273
	,COMMA=274
	,LEFT_GROUP=275
	,RIGHT_GROUP=276
	,STRING=277
	,ID=278
	,FLOATING=279
	,INTEGER=280
	,UNDEFINED=281


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NEW_LINE=258;
const int YY_parse_CLASS::READ=259;
const int YY_parse_CLASS::WRITE=260;
const int YY_parse_CLASS::WHILE=261;
const int YY_parse_CLASS::IF=262;
const int YY_parse_CLASS::TYPE=263;
const int YY_parse_CLASS::BOOL=264;
const int YY_parse_CLASS::END=265;
const int YY_parse_CLASS::SUM=266;
const int YY_parse_CLASS::MINUS=267;
const int YY_parse_CLASS::DIV=268;
const int YY_parse_CLASS::MULT=269;
const int YY_parse_CLASS::REL_OP=270;
const int YY_parse_CLASS::ASSIGN=271;
const int YY_parse_CLASS::SEMI_COLON=272;
const int YY_parse_CLASS::COLON=273;
const int YY_parse_CLASS::COMMA=274;
const int YY_parse_CLASS::LEFT_GROUP=275;
const int YY_parse_CLASS::RIGHT_GROUP=276;
const int YY_parse_CLASS::STRING=277;
const int YY_parse_CLASS::ID=278;
const int YY_parse_CLASS::FLOATING=279;
const int YY_parse_CLASS::INTEGER=280;
const int YY_parse_CLASS::UNDEFINED=281;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		69
#define	YYFLAG		-32768
#define	YYNTBASE	27

#define YYTRANSLATE(x) ((unsigned)(x) <= 281 ? yytranslate[x] : 48)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     6,     8,    10,    12,    16,    20,    24,
    28,    31,    32,    34,    36,    38,    41,    45,    48,    51,
    55,    57,    59,    61,    63,    65,    68,    69,    73,    77,
    80,    81,    85,    89,    91,    93,    95,    99,   101,   103,
   105
};

static const short yyrhs[] = {    -1,
    28,    27,     0,    34,     0,    33,     0,    31,     0,     6,
     0,    29,    46,    18,     0,    30,    27,    10,     0,     7,
    46,    18,     0,    32,    27,    10,     0,    35,    17,     0,
     0,    37,     0,    36,     0,    38,     0,     8,    23,     0,
    23,    16,    40,     0,     4,    23,     0,     5,    39,     0,
     5,    39,     3,     0,    22,     0,    23,     0,    22,     0,
    41,     0,     9,     0,    43,    42,     0,     0,    11,    43,
    42,     0,    12,    43,    42,     0,    45,    44,     0,     0,
    14,    45,    44,     0,    13,    45,    44,     0,    23,     0,
    25,     0,    24,     0,    20,    41,    21,     0,    47,     0,
     9,     0,    23,     0,    41,    15,    41,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    75,    77,    80,    82,    92,   106,   113,   131,   137,   156,
   163,   167,   169,   170,   171,   175,   189,   277,   299,   301,
   307,   314,   331,   347,   355,   374,   396,   398,   434,   475,
   496,   498,   535,   574,   587,   591,   595,   601,   606,   617,
   647
};

static const char * const yytname[] = {   "$","error","$illegal.","NEW_LINE",
"READ","WRITE","WHILE","IF","TYPE","BOOL","END","SUM","MINUS","DIV","MULT","REL_OP",
"ASSIGN","SEMI_COLON","COLON","COMMA","LEFT_GROUP","RIGHT_GROUP","STRING","ID",
"FLOATING","INTEGER","UNDEFINED","function_behavior","function_behavior_alpha",
"while_key_word","loop_init","loop","if_init","if_statement","function_line",
"function_line_alpha","var_init","var_assign","method_call","write_parameter",
"expression","numerical_expression","numerical_expression_prime","term","term_prime",
"factor","bool_expression","rel_expression",""
};
#endif

static const short yyr1[] = {     0,
    27,    27,    28,    28,    28,    29,    30,    31,    32,    33,
    34,    35,    35,    35,    35,    36,    37,    38,    38,    38,
    39,    39,    40,    40,    40,    41,    42,    42,    42,    43,
    44,    44,    44,    45,    45,    45,    45,    46,    46,    46,
    47
};

static const short yyr2[] = {     0,
     0,     2,     1,     1,     1,     1,     3,     3,     3,     3,
     2,     0,     1,     1,     1,     2,     3,     2,     2,     3,
     1,     1,     1,     1,     1,     2,     0,     3,     3,     2,
     0,     3,     3,     1,     1,     1,     3,     1,     1,     1,
     3
};

static const short yydefact[] = {     1,
     0,     0,     6,     0,     0,     0,     1,     0,     1,     5,
     1,     4,     3,     0,    14,    13,    15,    18,    21,    22,
    19,    39,     0,    34,    36,    35,     0,    27,    31,     0,
    38,    16,     0,     2,     0,     0,     0,    11,    20,    34,
     0,     0,     0,     0,    26,     0,     0,    30,     9,    25,
    23,    17,    24,     7,     8,    10,    37,    41,    27,    27,
    31,    31,    28,    29,    33,    32,     0,     0,     0
};

static const short yydefgoto[] = {    34,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    17,    21,    52,    27,    45,    28,    48,    29,    30,    31
};

static const short yypact[] = {    -4,
   -15,    -6,-32768,     5,   -11,    11,    -4,     5,    -4,-32768,
    -4,-32768,-32768,    19,-32768,-32768,-32768,-32768,-32768,-32768,
    41,-32768,   -14,    29,-32768,-32768,    33,    20,    25,    31,
-32768,-32768,    -2,-32768,    32,    42,    43,-32768,-32768,-32768,
    30,   -14,   -14,   -14,-32768,   -14,   -14,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    20,    20,
    25,    25,-32768,-32768,-32768,-32768,    54,    55,-32768
};

static const short yypgoto[] = {    26,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   -18,   -26,    -3,   -19,    -1,    48,-32768
};


#define	YYLAST		56


static const short yytable[] = {     1,
     2,     3,     4,     5,    41,    23,    50,    18,    40,    25,
    26,    32,   -12,    22,    53,    19,    20,    23,     6,    51,
    40,    25,    26,    58,    23,    67,    33,    24,    25,    26,
    43,    44,    63,    64,    36,    38,    37,    46,    47,    59,
    60,    65,    66,    39,    61,    62,   -40,    42,    49,    54,
    57,    55,    56,    68,    69,    35
};

static const short yycheck[] = {     4,
     5,     6,     7,     8,    23,    20,     9,    23,    23,    24,
    25,    23,    17,     9,    33,    22,    23,    20,    23,    22,
    23,    24,    25,    42,    20,     0,    16,    23,    24,    25,
    11,    12,    59,    60,     9,    17,    11,    13,    14,    43,
    44,    61,    62,     3,    46,    47,    18,    15,    18,    18,
    21,    10,    10,     0,     0,     8
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 4:
#line 83 "Parser.y"
{
        res = Table.delete_scope();
        if(res.error)
        {
            semantic_error(res);
        }
        excalibur_builder->if_ends();
        
    ;
    break;}
case 5:
#line 93 "Parser.y"
{
        res = Table.delete_scope();
        if(res.error)
        {
            semantic_error(res);
        }
        excalibur_builder->while_ends();
        
    ;
    break;}
case 6:
#line 108 "Parser.y"
{
        excalibur_builder->while_starts();
    ;
    break;}
case 7:
#line 115 "Parser.y"
{
        res = Table.new_scope();
        if(res.error)
            semantic_error(res);
        else{
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[-1].expression_node);
            res = *casted_ptr;
            if(!res.error){
                //Write IR code
                int sym_link_to_condition = res.sym_link;
                excalibur_builder->if_starts(sym_link_to_condition);
            }
        }
    ;
    break;}
case 9:
#line 139 "Parser.y"
{
        res = Table.new_scope();
        if(res.error)
            semantic_error(res);
        else{
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[-1].expression_node);
                                        
            res = *casted_ptr;
            if(!res.error){
                cout<<"llega...";
                //Write IR code
                int sym_link_to_condition = res.sym_link;
                excalibur_builder->if_starts(sym_link_to_condition);
            }
        }            
    ;
    break;}
case 16:
#line 177 "Parser.y"
{
        int sym_link = excalibur_builder->add_static_declaration(yyvsp[-1].text);
        res = Table.insert(yyvsp[0].text, yyvsp[-1].text, sym_link);
        if(res.error)
            semantic_error(res);
        string type(yyvsp[-1].text);
        string id(yyvsp[0].text);
        string new_line = type+" "+id;
        block_stack.add_line(new_line);
    ;
    break;}
case 17:
#line 191 "Parser.y"
{
        string type1 = "";
        string type2 = "";
        int variable_link=0;
        string tree_result_data;
        int tree_result_link;
        bool tree_result_is_constant;

        res = Table.get_type(yyvsp[-2].text);
        if(res.error)
        {
            semantic_error(res);
            type1 = "undefined";
        }
        else
        {
            type1 = res.attribute;
            variable_link = res.sym_link;
            semantic_result* casted_ptr = static_cast<semantic_result *> (yyvsp[0].expression_node);
            res = *casted_ptr;
            if(res.error)
            {
                semantic_error(res);
                type2 = "undefined";
            }
            else
            {
                type2 = res.attribute;
                tree_result_is_constant = res.is_constant;
                if(tree_result_is_constant)
                    tree_result_data = res.data;
                else
                    tree_result_link = res.sym_link;
                
                res = get_type_relation(type1, type2);
                if(res.error)
                {
                    semantic_error(res);
                }
                else//Write IR code
                {
                    //Type conversions
                    if(type1 == "float"){
                        if(type2 == "int"){
                            if(tree_result_is_constant){
                                tree_result_data = strcat(to_char_ptr(tree_result_data), ".0");
                            }else{
                                tree_result_link = excalibur_builder->int_to_double(tree_result_link);
                            }
                            type2 = "float";
                        }
                        //bools and strings do not get here
                        if(tree_result_is_constant){
                            excalibur_builder->store_value_in_variable(variable_link,"float", yyvsp[-2].text, tree_result_data);
                        }else{
                            excalibur_builder->store_link_in_variable(variable_link,"float", tree_result_link);
                        }
                    }else if(type1 == "int"){
                        if(type2 == "float"){
                            if(tree_result_is_constant){
                                double casted_tree_data = stod(tree_result_data);
                                int casted_tree_data_int = static_cast<int> (casted_tree_data);
                                tree_result_data = to_string(casted_tree_data_int);
                            }else{
                                tree_result_link = excalibur_builder->double_to_int(tree_result_link);
                            }
                        type2 = "int";
                        }
                    }

                    //storing values
                    if(tree_result_is_constant){
                        excalibur_builder->store_value_in_variable(variable_link,type1, yyvsp[-2].text, tree_result_data);
                    }else{
                        if(type1 == "string"){
                            excalibur_builder->store_link_to_string_variable(variable_link, tree_result_link);
                        }else{
                            excalibur_builder->store_link_in_variable(variable_link, type1, tree_result_link);
                        }
                    }
                }
            }
        }
    ;
    break;}
case 18:
#line 280 "Parser.y"
{
        res = Table.get_type(yyvsp[0].text);
        if(res.error)
            semantic_error(res);
        else{
            int sym_link = res.sym_link;
            string type = res.attribute;
            if(type == "bool"){
                semantic_result res;
                res.error = true;
                res.message = "Cannot read a bool value";
                semantic_error(res);
            }else{
                //Call a excalibur_builder that calls the scanf/fgets function
                excalibur_builder->read_variable(sym_link, type);
            }
        } 
    ;
    break;}
case 20:
#line 302 "Parser.y"
{
        excalibur_builder->print_new_line();
    ;
    break;}
case 21:
#line 309 "Parser.y"
{
        string text(yyvsp[0].text);
        //Calls a excalibur_builder that calls the printf function for constant strings
        excalibur_builder->print_constant_string(text);
    ;
    break;}
case 22:
#line 315 "Parser.y"
{
        res = Table.get_type(yyvsp[0].text);
        if(res.error)
            semantic_error(res);
        else{
            int sym_link = res.sym_link;
            string type = res.attribute;
            //Call a excalibur_builder that calls the printf function
            excalibur_builder->print_variable(sym_link, type);
        }
    ;
    break;}
case 23:
#line 333 "Parser.y"
{
        string text(yyvsp[0].text);
        //eliminate the quotes
        text.erase(0,1);
        text.erase(text.length()-1,1);
        cout<<"text:"<<text<<endl;
        semantic_result* res = new semantic_result;
        res->error = false;
        res->attribute = "string";
        res->data = to_char_ptr(text);
        res->is_constant = true;
        res->sym_link = -1;
        yyval.expression_node = res; 
    ;
    break;}
case 24:
#line 348 "Parser.y"
{
        semantic_result Node_res;        
        node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
        Node_res = casted_ptr -> define_type(0, excalibur_builder); 
        semantic_result* res = new semantic_result(Node_res);
        yyval.expression_node = res;
    ;
    break;}
case 25:
#line 356 "Parser.y"
{
    string bool_value(yyvsp[0].text);
    semantic_result* res = new semantic_result;
    res->error = false;
    res->attribute = "bool";
    if(bool_value == "true")
        res->data = "1";
    else
        res->data = "0";
    res->is_constant = true;
    res->sym_link = -1;
    yyval.expression_node = res;
;
    break;}
case 26:
#line 376 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            yyval.expression_node = yyvsp[-1].expression_node;
        }
        else
        {
            //assigning $1 (factor) as the leftmost leave of the $2 (term_prime) tree
            //first, two auxiliar pointer casted as node*
            node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
            node* casted_ptr2 = static_cast<node *> (yyvsp[-1].expression_node);

            //Then,from casted_ptr we call insert_left_most
            casted_ptr -> insert_left_most(casted_ptr2);
            yyval.expression_node = casted_ptr;            
        }
    ;
    break;}
case 27:
#line 397 "Parser.y"
{yyval.expression_node = nullptr;
    break;}
case 28:
#line 399 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);
            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 29:
#line 435 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 30:
#line 477 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            yyval.expression_node = yyvsp[-1].expression_node;
        }
        else
        {
            //assigning $1 (factor) as the leftmost leave of the $2 (term_prime) tree
            //first, two auxiliar pointer casted as node*
            node* casted_ptr = static_cast<node *> (yyvsp[0].expression_node);
            node* casted_ptr2 = static_cast<node *> (yyvsp[-1].expression_node);

            //Then,from casted_ptr we call insert_left_most
            casted_ptr -> insert_left_most(casted_ptr2);
            yyval.expression_node = casted_ptr;            
        }
    ;
    break;}
case 31:
#line 497 "Parser.y"
{yyval.expression_node = nullptr;
    break;}
case 32:
#line 499 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 33:
#line 536 "Parser.y"
{
        if(yyvsp[0].expression_node == nullptr)
        {
            // The operator becomes the root node of a new three
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 node, here it's being assign as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);
            yyval.expression_node = ptr;
        }
        else
        {
            //Realizar una operacion entre $3 y $2 --> Comprobacion de tipos
            // res = type_system_numeric($3,$2,operator_aux);
            
            // The operator becomes the root node of a new tree
            node* ptr = new node(yyvsp[-2].text);

            //$2 is currently a void pointer, here it's beeing casted as a node pointer
            node* casted_ptr = static_cast<node *> (yyvsp[-1].expression_node);

            //casted_ptr points to $2 (factor) node, here it's being assigned as the right son of the new tree
            ptr -> assign_right_node(casted_ptr);

            //assigning the new tree as the leftmost leave of the $3 tree
            //first, an auxiliar pointer casted as node*
            node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);

            //Then,from casted_ptr2 we call insert_left_most
            casted_ptr2 -> insert_left_most(ptr);
            yyval.expression_node = casted_ptr2;
        }
    ;
    break;}
case 34:
#line 576 "Parser.y"
{            
        res = Table.get_type(yyvsp[0].text);
        if(!res.error)
        {
            yyval.expression_node = new node(yyvsp[0].text,to_char_ptr(res.attribute), res.sym_link);
        }
        else
        {
            yyval.expression_node = new node(yyvsp[0].text);
        }
    ;
    break;}
case 35:
#line 588 "Parser.y"
{
        yyval.expression_node = new node(yyvsp[0].text,"int", true);
    ;
    break;}
case 36:
#line 592 "Parser.y"
{
        yyval.expression_node = new node(yyvsp[0].text,"float", true);
    ;
    break;}
case 37:
#line 596 "Parser.y"
{
        yyval.expression_node = yyvsp[-1].expression_node;
    ;
    break;}
case 38:
#line 603 "Parser.y"
{
        yyval.expression_node = yyvsp[0].expression_node;
    ;
    break;}
case 39:
#line 607 "Parser.y"
{
        semantic_result* res_bool = new semantic_result;
        string bool_value(yyvsp[0].text);
        int sym_link_to_result = excalibur_builder->load_constant_bool(bool_value);
        res_bool->error = false;
        res_bool->attribute = "bool";
        res_bool->sym_link = sym_link_to_result;
        res_bool->is_constant = false;        
        yyval.expression_node = res_bool;
    ;
    break;}
case 40:
#line 618 "Parser.y"
{
        semantic_result res_bool_local;
        res = Table.get_type(yyvsp[0].text);
        if(res.error){
            semantic_error(res);
            yyval.expression_node = &res;
        }    
        else{
            int sym_link_to_result = res.sym_link;
            string type = res.attribute;
            if(type != "bool"){
                res_bool_local.error = true;
                res_bool_local.message = "Cannot use a non-bool variable as a condition";
                semantic_error(res_bool_local);
                yyval.expression_node = &res;
            }else{
                sym_link_to_result = excalibur_builder->load_bool_variable_for_condition(sym_link_to_result);

                res_bool_local.error = false;
                res_bool_local.attribute = "bool";
                res_bool_local.sym_link = sym_link_to_result;
                res_bool_local.is_constant = false;

                semantic_result* res_bool = new semantic_result(res_bool_local);
                yyval.expression_node = res_bool;
            }
        }
    ;
    break;}
case 41:
#line 649 "Parser.y"
{
        string op(yyvsp[-1].text);
        node* casted_ptr = static_cast<node *> (yyvsp[-2].expression_node);
        node* casted_ptr2 = static_cast<node *> (yyvsp[0].expression_node);
        int sym_link_to_condition_corrected = excalibur_builder->get_sym_link_count();
        res = casted_ptr -> define_type(0, excalibur_builder);
        if(res.error){
            semantic_error(res);
            yyval.expression_node = &res;
        }
        else{
            //getting the first expression data
            bool is_constant_1 = res.is_constant;
            string type_1 = res.attribute;
            string data_1;
            int sym_link_1;

            if(is_constant_1)
                data_1 = res.data;
            else
                sym_link_1 = res.sym_link;

            res = casted_ptr2 -> define_type(1, excalibur_builder);
            if(res.error){
                semantic_error(res);
                yyval.expression_node = &res;    
            }else{
                bool is_constant_2 = res.is_constant;
                string type_2 = res.attribute;
                string data_2;
                int sym_link_2;
                if(is_constant_2)
                    data_2 = res.data;
                else
                    sym_link_2 = res.sym_link;

                //Checking if the types are compatible (defining the expression's type)
                res = get_type_relation_for_rel_ops(type_1, type_2);
                if(res.error){
                    semantic_error(res);
                    yyval.expression_node = &res;
                }else{
                    string rel_expression_type = res.attribute;
                    //making type conversions
                    if(rel_expression_type == "float"){
                        if(type_1 == "int"){
                            if(is_constant_1){
                                data_1 = strcat(to_char_ptr(data_1), ".0");
                            }else{
                                sym_link_1 = excalibur_builder->int_to_double(sym_link_1);
                            }
                            type_1 = "float";
                        }
                        if(type_2 == "int"){
                            if(is_constant_2){
                                data_2 = strcat(to_char_ptr(data_2), ".0");
                            }else{
                                sym_link_2 = excalibur_builder->int_to_double(sym_link_2);
                            }
                            type_2 = "float";
                        }
                    }
                    
                    //writing IR according to the type of the expression and operands properties
                    int sym_link_to_condition;
                    if(is_constant_1){
                        if(is_constant_2){
                            sym_link_to_condition = excalibur_builder->constant_to_constant_operation(data_1, data_2, op, type_1);
                        }else{
                            sym_link_to_condition = excalibur_builder->constant_to_link_operation(data_1, sym_link_2, op, type_1);   
                        }
                    }else{
                        if(is_constant_2){
                            sym_link_to_condition = excalibur_builder->link_to_constant_operation(sym_link_1, data_2, op, type_1);
                        }else{
                            sym_link_to_condition = excalibur_builder->link_to_link_operation(sym_link_1, sym_link_2, op, type_1);
                        }
                    }
                    semantic_result res_bool_local;
                    res_bool_local.error = false;
                    res_bool_local.attribute = "bool";
                    res_bool_local.sym_link = sym_link_to_condition;
                    res_bool_local.is_constant = false;

                    semantic_result* res_bool = new semantic_result(res_bool_local);
                    yyval.expression_node = res_bool;
                }
            } 
        }        
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 741 "Parser.y"


void semantic_error(semantic_result res)
{
    try{
        error_count++;
        cout<<"\n---semantic error in line "<<yylineno<<" : << "<<lineBuffer<< " >> "<<res.message<<" ---";
        // cout<<"???"<<endl;
    }catch (exception& e){
        cout<<"Exception: "<<e.what()<<endl;
    }
}

void yyerror (char* s)
{
    error_count++;
    printf("\n---%s in line %d : << %s >>---", s, yylineno, lineBuffer);
}

char* to_char_ptr (const string& str)
{
    char* char_ptr = new char[str.length() +1];
    strcpy(char_ptr, str.c_str());
    return char_ptr;
}

semantic_result get_type_relation(string type1, string type2)
{
    semantic_result res;
    if(type1 == "string" && type2 == "string")
    {
        res.error = false;
    }
    else if(type1 == "int" && type2 == "int")
    {
        res.error = false;
    }
    else if(type1 == "float" && type2 == "float")
    {
        res.error = false;
    }
    else if(type1 == "bool" && type2 == "bool")
    {
        res.error = false;
    }
    else if(type1 == "float" && type2 == "int")
    {
        res.error = false;
    }
    else if(type1 == "int" && type2 == "float")
    {
        res.error = false;
    }
    else
    {
        res.error = true;
        res.message = "Incompatible types in assigning operation.";
    }
    return res;
}

semantic_result get_type_relation_for_rel_ops(string type1, string type2){
    semantic_result res;
    //only ints and floats can be compared
    if(type1 == "int" && type2 == "int"){
        res.error = false;
        res.attribute = "int";
    }
    else if(type1 == "float" && type2 == "float"){
        res.error = false;
        res.attribute = "float";
    }
    else if(type1 == "float" && type2 == "int"){
        res.error = false;
        res.attribute = "float";
    }
    else if(type1 == "int" && type2 == "float"){
        res.error = false;
        res.attribute = "float";
    }
    else{
        res.error = true;
        res.message = "Incompatible types in relational operation.";
    }

    return res;
}

int main(int argc, char** argv) {
    clock_t start_time, end_time;
    double execution_time;

    start_time = clock();  // Get the initial clock time

    FILE* file = fopen(argv[1], "r");
    if (!file) {
        perror("fopen");
        return 1;
    }

    yyin = file;

    yyparse();

    fclose(file);

    end_time = clock();  // Get the final clock time*

    // Calculate the execution time in seconds
    execution_time = (double)(end_time - start_time) / CLOCKS_PER_SEC;

    if(error_count==0){
        block_stack.write_file("IR.txt");
        string file_name(argv[1]);
        string file_name_no_extension = file_name.substr(0, file_name.find("."));
        string file_name_ll = file_name_no_extension + ".ll";
        excalibur_builder->generate_llvm_IR_file(file_name_ll);
        
        string command = "clang -o "+file_name_no_extension+" -x ir "+file_name_ll;

        system(command.c_str());        
        
        cout<<"Compiling time: "<<execution_time<<" seconds"<<endl;
        cout<<"Files "<<file_name_no_extension<<" and "<<file_name_ll<<" generated successfuly."<<endl;
    }

    return 0;
}
